---

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Ensure system dependences are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_dependences }}"

- name: Ensure the caching server (memcached) is installed
  yum:
    name: memcached
    state: present