---

# The user is the operating system user the command is executed with. 
# In our case it will be root for most of the time or openproject.

# If you find any bugs or you have any recommendations for improving this tutorial,
#  please, feel free to create a pull request against this guide.

- name: User configurations 
  include_tasks: pre-tasks/user.yml

- name: Configure dependencies
  include_tasks: pre-tasks/dependencies.yml

- name: Install PostgreSQL
  include_tasks: pre-tasks/postgresql.yml

- name: Install & configure Ruby
  include_tasks: pre-tasks/ruby.yml

- name: Install & configure  NodeJS
  include_tasks: pre-tasks/node.yml

- name: Install OpenProject
  include_tasks: setup.yml

- name: Configure OpenProject
  include_tasks: configuration.yml

- name: Post configuration of the environment
  include_tasks: post-tasks/configuration.yml

- name: Install & configure Apache & Passenger
  include_tasks: post-tasks/apache-passenger.yml

- name: Configure background jobs
  include_tasks: post-tasks/background-jobs.yml

