---

# Installation of Node
# The are several possibilities to install Node on your machine. We will use nodenv. 
# Please run su openproject --login if you are the root user. 
# If you are already the openproject user you can skip this command. 
# Please be aware that the actual installation of a specific node version takes some time to finish.

# [openproject@host] git clone https://github.com/OiNutter/nodenv.git ~/.nodenv
# [openproject@host] echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.profile
# [openproject@host] echo 'eval "$(nodenv init -)"' >> ~/.profile
# [openproject@host] source ~/.profile
# [openproject@host] git clone git://github.com/OiNutter/node-build.git ~/.nodenv/plugins/node-build

# [openproject@host] nodenv install 8.12.0
# [openproject@host] nodenv rehash
# [openproject@host] nodenv global 8.12.0
# To check our Node installation we run node --version. It should output something very similar to:

# v8.12.0

- name: Clone node environment repository
  git:
    repo: https://github.com/OiNutter/nodenv.git
    dest: ~/.nodenv
  become_user: "{{ openproject_user }}"

- name: Add nodenv to the PATH
  shell: |
    echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.profile
    echo 'eval "$(nodenv init -)"' >> ~/.profile
  become_user: "{{ openproject_user }}"

- name: Source the ~/.profile file
  shell: source ~/.profile
  become_user: "{{ openproject_user }}"

- name: Clone node build repository
  git:
    repo: git://github.com/OiNutter/node-build.git
    dest: ~/.nodenv/plugins/node-build
  become_user: "{{ openproject_user }}"

- name: Install node
  shell: |
    nodenv install 8.12.0
    nodenv rehash
    nodenv global 8.12.0
  become_user: "{{ openproject_user }}"

