---

# Installation of Node
# The are several possibilities to install Node on your machine. We will use nodenv. 
# Please run su openproject --login if you are the root user. 
# If you are already the openproject user you can skip this command. 
# Please be aware that the actual installation of a specific node version takes some time to finish.

# [openproject@host] git clone https://github.com/OiNutter/nodenv.git ~/.nodenv
# [openproject@host] echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.profile
# [openproject@host] echo 'eval "$(nodenv init -)"' >> ~/.profile
# [openproject@host] source ~/.profile
# [openproject@host] git clone git://github.com/OiNutter/node-build.git ~/.nodenv/plugins/node-build

# [openproject@host] nodenv install 8.12.0
# [openproject@host] nodenv rehash
# [openproject@host] nodenv global 8.12.0
# To check our Node installation we run node --version. It should output something very similar to:

# v8.12.0

- name: Clone node environment repository
  git:
    repo: https://github.com/OiNutter/nodenv.git
    dest: ~/.nodenv
  become_user: "{{ openproject_user }}"
  become: yes


- name: Add nodenv to the PATH
  become_user: "{{ openproject_user }}"
  become: yes
  lineinfile:
    path: ~/.bashrc
    line: |
      export PATH="$HOME/.nodenv/bin:$PATH"
      eval "$(nodenv init -)"

- name: Source the ~/.bashrc file
  shell: source ~/.bashrc
  become: yes
  become_user: "{{ openproject_user }}"

- name: Clone node build repository
  git:
    repo: https://github.com/OiNutter/node-build.git
    dest: ~/.nodenv/plugins/node-build
  become_user: "{{ openproject_user }}"
  become: yes

- name: Install node
  shell: |
    nodenv install 12.19.0
    nodenv rehash
    nodenv global 12.19.0
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"