---

# Create a dedicated OpenProject user
# sudo groupadd openproject
# sudo useradd --create-home --gid openproject openproject
# sudo passwd openproject #(enter desired password)

- name: Create openproject group
  group:
    name: '{{openproject_group}}'
    system: yes
  become: yes

- name: Create openproject user
  user:
    name: '{{openproject_user}}'
    group: '{{openproject_group}}'
    system: yes
  become: yes