---

# Serve OpenProject with Apache and Passenger
# First, we exit the current bash session with the openproject user, 
# so that we are again in a root shell.

# [openproject@ubuntu] exit
# Then, we prepare apache and passenger:

# [root@host] apt-get install -y apache2 libcurl4-gnutls-dev      \
#                                apache2-dev libapr1-dev \
#                                libaprutil1-dev
# [root@ubuntu] chmod o+x "/home/openproject"


- name: Ensure httpd is installed
  become: yes
  yum:
    name: "{{ apache_dependencies }}"
    state: present
  when: not is_apache_installed

- name: enable service httpd and ensure it is not masked
  become: yes
  systemd:
    name: httpd
    enabled: yes
    masked: no
  when: not is_apache_installed


# Now, the Passenger gem is installed and integrated into apache.

# [root@ubuntu] su openproject --login
# [openproject@ubuntu] cd ~/openproject
# [openproject@ubuntu] gem install passenger
# [openproject@ubuntu] passenger-install-apache2-module
# If you are running on a Virtual Private Server, you need to make sure 
# you have at least 1024mb of RAM before running the passenger-install-apache2-module.

# Follow the instructions passenger provides. The passenger installer 
# will ask you the question in “Which languages are you interested in?”. 
# We are interested only in ruby.

- name: Passenger install apache2 module
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"
  shell:
    cmd: gem install passenger && passenger-install-apache2-module --auto --language Ruby
    chdir: ~/openproject

# The passenger installer tells us to edit the apache config files. To do this, continue as the root user:v
# [openproject@host] exit

# As told by the installer, create the file /etc/apache2/mods-available/passenger.load and add the following line. 
# But before copy&pasting the following lines, check if the content (especially the version numbers!) 
# is the same as the passenger-install-apache2-module installer said. When you’re in doubt, do what passenger tells you.

# LoadModule passenger_module /home/openproject/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/passenger-5.0.14/buildout/apache2/mod_passenger.so

- name: Get rbenv version from shell
  shell: rbenv version
  register: rbenv_result
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"

- name: Get gem version from shell
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"  
  shell: gem --version
  register: gem_result

- name: Get passenger version from shell
  become: yes
  become_user: "{{ openproject_user }}"
  become_flags: "-i"
  shell: passenger -v
  register: passenger_result

- set_fact:
    rbenv_version: '{{ rbenv_result.stdout | regex_search("^([0-9]+\\.)?([0-9]+\\.)?(\\*|[0-9]+)") }}'
    gem_version: '{{ gem_result.stdout | regex_search("^([0-9]+\\.)?([0-9]+\\.)?(\\*|[0-9]+)") }}'
    passenger_version: '{{ passenger_result.stdout | regex_search("^([0-9]+\\.)?([0-9]+\\.)?(\\*|[0-9]+)") }}'

- name: Ensure /etc/httpd/sites-available/openproject.conf is created
  become: yes
  template:
    src: openproject.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: '{{ openproject_user }}'
    group: '{{ openproject_group }}'
    mode: '0644'

- name: Insert LoadModule a line in /etc/httpd/conf/httpd.conf
  become: yes
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "LoadModule passenger_module /home/openproject/.rbenv/versions/{{ rbenv_version }}/lib/ruby/gems/{{ gem_version }}/gems/passenger-{{ passenger_version }}/buildout/apache2/mod_passenger.so"


- name: Ensure /etc/httpd/conf.d/passenger.conf is created
  become: yes
  template:
    src: passenger.conf.j2
    dest: /etc/httpd/conf.d/passenger.conf
    owner: '{{ openproject_user }}'
    group: '{{ openproject_group }}'
    mode: '0644'

# Now, we (re-)start Apache:

# - name: Restart service httpd, in all cases
#   become: yes
#   systemd:
#     name: httpd.service
#     state: restarted

- shell: systemctl start httpd.service

# Your OpenProject installation should be accessible on port 80 (http). 
# A default admin-account is created for you having the following credentials:

# Username: admin Password: admin

# Please, change the password on the first login. 
# Also, we highly recommend to configure the SSL module in Apache for https communication.