---

# Activate background jobs

- name: Get Ruby version
  become: yes
  shell: ruby -v
  register: ruby_result

- set_fact:
    ruby_version: "{{ 'ruby_result.stdout' | regex_search('^(\d+\.)?(\d+\.)?(\*|\d+)') }}"

# OpenProject sends (some) mails asynchronously by using background jobs. 
# All such jobs are collected in a queue, so that a separate process can work on them. 
# This means that we have to start the background worker. 
# To automate this, we put the background worker into a cronjob.

# [root@all] su - openproject -c "bash -l"
# [openproject@all] crontab -e
# Now, the crontab file opens in the standard editor. Add the following entry to the file:

# */1 * * * * cd /home/openproject/openproject; /home/openproject/.rvm/gems/ruby-2.1.5/wrappers/rake jobs:workoff
# This will start the worker job every minute.

- name: Activate background jobs 
  cron:
    name: "OpenProject background jobs"
    minute: "1"
    job: "cd /home/openproject/openproject; /home/openproject/.rvm/gems/ruby-{{ ruby_version }}/wrappers/rake jobs:workoff"