---

# Finish the installation of OpenProject

# [openproject@host] cd ~/openproject
# [openproject@host] RAILS_ENV="production" ./bin/rake db:create
# [openproject@host] RAILS_ENV="production" ./bin/rake db:migrate
# [openproject@host] RAILS_ENV="production" ./bin/rake db:seed
# [openproject@host] RAILS_ENV="production" ./bin/rake assets:precompile
# NOTE: When not specified differently, the default data loaded via db:seed will have an english localization.
#  You can choose to seed in a different language by specifying the language via the
#   LOCALE environment variable on the call to db:seed. E.g.

# [openproject@all] RAILS_ENV="production" LOCALE=fr ./bin/rake db:seed
# will seed the database in the french language.

# Secret token

# You need to generate a secret key base for the production environment
# with ./bin/rake secret and make that available through the environment variable SECRET_KEY_BASE. 
# In this installation guide, we will use the local .profile of the OpenProject user. 
# You may alternatively set the environment variable in /etc/environment or pass it to the server 
# upon start manually in /etc/apache2/envvars.

# [openproject@host] echo "export SECRET_KEY_BASE=$(./bin/rake secret)" >> ~/.profile
# [openproject@host] source ~/.profile

# - name: Ensure Rails environment is configured [env RAILS_ENV="production" ./bin/rake db:create]
#   shell: env RAILS_ENV="production" ./bin/rake db:create
#   args:
#     chdir: ~/openproject
#   environment:
#     RAILS_ENV: "production"
#   become: yes
#   become_user: "{{ openproject_user }}"
#   become_flags: "-i"

# - name: Ensure Rails environment is configured [env RAILS_ENV="production" ./bin/rake db:migrate]
#   shell: env RAILS_ENV="production" ./bin/rake db:migrate
#   args:
#     chdir: ~/openproject
#   environment:
#     RAILS_ENV: "production"
#   become: yes
#   become_user: "{{ openproject_user }}"
#   become_flags: "-i"

# - name: Ensure Rails environment is configured [env RAILS_ENV="production" ./bin/rake db:seed]
#   shell: env RAILS_ENV="production" ./bin/rake db:seed
#   args:
#     chdir: ~/openproject
#   environment:
#     RAILS_ENV: "production"
#   become: yes
#   become_user: "{{ openproject_user }}"
#   become_flags: "-i"

# - name: Ensure Rails environment is configured [env RAILS_ENV="production" ./bin/rake assets:precompile]
#   shell: env RAILS_ENV="production" ./bin/rake assets:precompile
#   args:
#     chdir: ~/openproject
#   environment:
#     RAILS_ENV: "production"
#   become: yes
#   become_user: "{{ openproject_user }}"
#   become_flags: "-i"

- name: set up database
  shell: cd ~/openproject && env RAILS_ENV="production" ./bin/rake db:create
  args:
    chdir: '~/openproject'
  # FIXME: from ansible v2.0.0 we can maybe use the bundler module
  become: yes
  become_user: '{{openproject_user}}'
  register: rake_db_create_all
  changed_when: '"already exists" not in rake_db_create_all.stderr'

- name: generate secret token
  shell: cd ~/openproject && env RAILS_ENV="production" ./bin/rake generate_secret_token
  args:
    chdir: '~/openproject'
    creates: '~/openproject/config/secret_token.yml'
  # FIXME: from ansible v2.0.0 we can maybe use the bundler module
  become: yes
  become_user: '{{openproject_user}}'

- name: migrate database
  shell: cd ~/openproject && env RAILS_ENV="production" ./bin/rake db:migrate
  args:
    chdir: '~/openproject'
  environment:
    RAILS_ENV: 'production'
  # FIXME: from ansible v2.0.0 we can maybe use the bundler module
  become: yes
  become_user: '{{openproject_user}}'
  register: generate_migration
  changed_when: generate_migration.stdout != ""

- name: seed database
  shell: cd ~/openproject && env RAILS_ENV="production" LOCALE="{{openproject_locale}}" ./bin/rake db:seed
  args:
    chdir: '~/openproject'
  environment:
    RAILS_ENV: 'production'
    LOCALE: '{{openproject_locale}}'
  # FIXME: from ansible v2.0.0 we can maybe use the bundler module
  become: yes
  become_user: '{{openproject_user}}'
  register: seed_database
  changed_when: '"Skipping" not in seed_database.stdout'


- name: Ruby precompile assets
  shell: cd ~/openproject && env RAILS_ENV="production" ./bin/rake assets:precompile
  args:
    chdir: '~/openproject'
  environment:
    RAILS_ENV: 'production'
  # FIXME: from ansible v2.0.0 we can maybe use the bundler module
  become: yes
  become_user: '{{ openproject_user }}'
  async: 3600
  poll: 1