---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    instance_name: "openproject-test"
    box: centos/7
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
      remote_tmp: /tmp/.ansible
  log: true
lint:
  name: yamllint
